# Producer Dockerfile

# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the producer code
COPY send.py /app

# Install dependencies
RUN pip install pika

# Run the producer script
CMD ["python3", "send.py"]
