FROM python:3.10.12-slim
COPY . .

RUN apt-get update
RUN apt-get -y install libpq-dev gcc
RUN python -m pip install --upgrade pip

# Copy the requirements file into the container
COPY requirements.txt requirements.txt

# Install the dependencies
RUN pip install -r requirements.txt
RUN pip install elasticsearch
RUN pip install pika

CMD ["python3","-u", "consumer.py" ]