# Consumer Dockerfile

# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the consumer code
COPY recive.py /app

# Install dependencies
RUN pip install pika

# Run the consumer script
CMD ["python3","recive.py"]
